# Project-wide Gradle settings.

# --- MEMORY FIX (Zaruri hai Build Error hatane ke liye) ---
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# --- YOUR SETTINGS ---
android.suppressUnsupportedCompileSdk=34
org.gradle.warning.mode=none
android.useAndroidX=true
android.enableJetifier=true

# Kotlin code style
kotlin.code.style=official

# Recommended for newer Android projects
android.nonTransitiveRClass=true
